from typing import Any, Dict


VARIANT_ALTERATION_ONTOLOGY: Dict[str, Dict[str, Any]] = {
    "missense": {
        "normalized_value": "missense",
        "definition": "A sequence variant that changes one amino acid to another without creating a stop codon.",
        "variant_class": "Sequence Variant",
        "parent_mechanism": "mutation",
        "minimal_location_type": "Amino Acid",
        "location_semantic": "container",
        "canonical_label": "missense mutation",
        "abbreviation": "",
        "is_umbrella": False,
        "regex_pattern": r"\bmissense(?:\s+mutation)?\b",
        "priority": 2,

    },
    "nonsense": {
        "normalized_value": "nonsense",
        "definition": "A sequence variant that creates a premature termination codon.",
        "variant_class": "Sequence Variant",
        "parent_mechanism": "truncating",
        "minimal_location_type": "Amino Acid",
        "location_semantic": "container",
        "canonical_label": "nonsense mutation",
        "abbreviation": "",
        "is_umbrella": False,
        "regex_pattern": r"\b(?:nonsense(?:\s+mutation)?|stop\s+gained)\b",
        "priority": 3,
    },
    "frameshift": {
        "normalized_value": "frameshift",
        "definition": "A coding sequence insertion or deletion that shifts the translation reading frame.",
        "variant_class": "Sequence Variant",
        "parent_mechanism": "truncating",
        "minimal_location_type": "Amino Acid",
        "location_semantic": "container",
        "canonical_label": "frameshift mutation",
        "abbreviation": "",
        "is_umbrella": False,
        "regex_pattern": r"\b(?:frameshift|frame\s*shift|fs)\b",
        "priority": 3,
    },
    "truncating": {
        "normalized_value": "truncating",
        "definition": "An umbrella sequence variant expected to shorten the encoded protein.",
        "variant_class": "Sequence Variant",
        "parent_mechanism": "mutation",
        "minimal_location_type": "Amino Acid",
        "location_semantic": "container",
        "canonical_label": "truncating mutation",
        "abbreviation": "",
        "is_umbrella": True,
        "regex_pattern": r"\btruncat(?:ing|ed)?(?:\s+mutation)?\b",
        "priority": 2,
    },
    "deletion": {
        "normalized_value": "deletion",
        "definition": "An umbrella sequence variant involving loss of nucleotides or amino acids; context is needed to distinguish it from copy-number deletion.",
        "variant_class": "Sequence Variant",
        "parent_mechanism": "mutation",
        "minimal_location_type": "Amino Acid",
        "location_semantic": "container",
        "canonical_label": "deletion",
        "abbreviation": "del",
        "is_umbrella": True,
        "regex_pattern": r"\b(?:deletion|del)\b",
        "priority": 2,
    },
    "inframe_deletion": {
        "normalized_value": "inframe_deletion",
        "definition": "A sequence deletion whose length preserves the coding reading frame.",
        "variant_class": "Sequence Variant",
        "parent_mechanism": "deletion",
        "minimal_location_type": "Amino Acid",
        "location_semantic": "container",
        "canonical_label": "in-frame deletion",
        "abbreviation": "",
        "is_umbrella": False,
        "regex_pattern": r"\b(?:in[\s\-]?frame\s+deletion|non[\s\-]?frameshift\s+deletion|deletion|del)\b",
        "priority": 3,
    },
    "insertion": {
        "normalized_value": "insertion",
        "definition": "An umbrella sequence variant involving insertion of nucleotides or amino acids.",
        "variant_class": "Sequence Variant",
        "parent_mechanism": "mutation",
        "minimal_location_type": "Amino Acid",
        "location_semantic": "container",
        "canonical_label": "insertion",
        "abbreviation": "ins",
        "is_umbrella": True,
        "regex_pattern": r"\b(?:insertion|ins)\b",
        "priority": 2,
    },
    "inframe_insertion": {
        "normalized_value": "inframe_insertion",
        "definition": "A sequence insertion whose length preserves the coding reading frame.",
        "variant_class": "Sequence Variant",
        "parent_mechanism": "insertion",
        "minimal_location_type": "Amino Acid",
        "location_semantic": "container",
        "canonical_label": "in-frame insertion",
        "abbreviation": "",
        "is_umbrella": False,
        "regex_pattern": r"\b(?:in[\s\-]?frame\s+insertion|non[\s\-]?frameshift\s+insertion|ins)\b",
        "priority": 3,
    },
    "duplication": {
        "normalized_value": "duplication",
        "definition": "An umbrella sequence variant in which a nucleotide or amino acid segment is repeated adjacent to the original segment.",
        "variant_class": "Sequence Variant",
        "parent_mechanism": "mutation",
        "minimal_location_type": "Amino Acid",
        "location_semantic": "container",
        "canonical_label": "duplication",
        "abbreviation": "dup",
        "is_umbrella": True,
        "regex_pattern": r"\b(?:duplication|dup)\b",
        "priority": 2,
    },
    "internal_tandem_duplication": {
        "normalized_value": "internal tandem duplication",
        "definition": "An in-frame tandem duplication occurring within a coding region or protein segment.",
        "variant_class": "Sequence Variant",
        "parent_mechanism": "inframe_insertion",
        "minimal_location_type": "Amino Acid",
        "location_semantic": "container",
        "canonical_label": "ITD",
        "abbreviation": "ITD",
        "is_umbrella": False,
        "regex_pattern": r"\b(?:internal(?:\s+|_)tandem(?:\s+|_)duplication|itd)\b",
        "priority": 3,
    },
    "splice": {
        "normalized_value": "splice",
        "definition": "An umbrella sequence variant that affects RNA splicing.",
        "variant_class": "Sequence Variant",
        "parent_mechanism": "mutation",
        "minimal_location_type": "Nucleotide",
        "location_semantic": "container",
        "canonical_label": "splice variant",
        "abbreviation": "spl",
        "is_umbrella": True,
        "regex_pattern": r"\bsplic(?:e|ing)\b",
        "priority": 2,
    },
    "splice_site": {
        "normalized_value": "splice_site",
        "definition": "A sequence variant affecting canonical or annotated splice-site positions.",
        "variant_class": "Sequence Variant",
        "parent_mechanism": "splice",
        "minimal_location_type": "Nucleotide",
        "location_semantic": "container",
        "canonical_label": "splice site variant",
        "abbreviation": "",
        "is_umbrella": True,
        "regex_pattern": r"\b(?:splice[\s\-]?site|splicing[\s\-]?site)\b",
        "priority": 3,
    },
    "splice_acceptor": {
        "normalized_value": "splice_acceptor",
        "definition": "A sequence variant affecting a splice acceptor site.",
        "variant_class": "Sequence Variant",
        "parent_mechanism": "splice_site",
        "minimal_location_type": "Nucleotide",
        "location_semantic": "container",
        "canonical_label": "splice acceptor variant",
        "abbreviation": "",
        "is_umbrella": False,
        "regex_pattern": r"\bsplice\s+acceptor\b",
        "priority": 3,
    },
    "splice_donor": {
        "normalized_value": "splice_donor",
        "definition": "A sequence variant affecting a splice donor site.",
        "variant_class": "Sequence Variant",
        "parent_mechanism": "splice_site",
        "minimal_location_type": "Nucleotide",
        "location_semantic": "container",
        "canonical_label": "splice donor variant",
        "abbreviation": "",
        "is_umbrella": False,
        "regex_pattern": r"\bsplice\s+donor\b",
        "priority": 3,
    },
    "splice_region": {
        "normalized_value": "splice_region",
        "definition": "A sequence variant in a region that may influence splicing but is not necessarily a canonical splice donor or acceptor.",
        "variant_class": "Sequence Variant",
        "parent_mechanism": "splice",
        "minimal_location_type": "Nucleotide",
        "location_semantic": "container",
        "canonical_label": "splice region variant",
        "abbreviation": "",
        "is_umbrella": False,
        "regex_pattern": r"\bsplice\s+region\b",
        "priority": 3,
    },
    "exon_skipping": {
        "normalized_value": "exon_skipping",
        "definition": "A splicing-related alteration that causes an exon to be skipped from the mature transcript.",
        "variant_class": "Sequence Variant",
        "parent_mechanism": "splice",
        "minimal_location_type": "Exon",
        "location_semantic": "container",
        "canonical_label": "skipping mutation",
        "abbreviation": "",
        "is_umbrella": False,
        "regex_pattern": r"\b(?:exon\s+\d+\s+skipping|exon\s+skipping|skip(?:ping)?)\b",
        "priority": 3,
    },
    "copy_number_change": {
        "normalized_value": "copy_number_change",
        "definition": "An umbrella copy-number alteration involving gain or loss of genomic copies.",
        "variant_class": "Copy Number Variant",
        "parent_mechanism": "mutation",
        "minimal_location_type": "Gene",
        "location_semantic": "target",
        "canonical_label": "copy number change",
        "abbreviation": "",
        "is_umbrella": True,
        "regex_pattern": r"\b(?:copy\s+number\s+(?:alteration|variation|change)|cna|cnv|gcn)\b",
        "priority": 1,
    },
    "copy_number_gain": {
        "normalized_value": "copy_number_gain",
        "definition": "An umbrella copy-number alteration involving increased genomic copy count.",
        "variant_class": "Copy Number Variant",
        "parent_mechanism": "copy_number_change",
        "minimal_location_type": "Gene",
        "location_semantic": "target",
        "canonical_label": "copy number gain",
        "abbreviation": "",
        "is_umbrella": True,
        "regex_pattern": r"\b(?:copy\s+number\s+gain|copy\s+gain|gain\s+of\s+copy\s+number)\b",
        "priority": 2,
    },
    "amplification": {
        "normalized_value": "amplification",
        "definition": "A copy-number gain, usually high-level, affecting a gene or locus.",
        "variant_class": "Copy Number Variant",
        "parent_mechanism": "copy_number_gain",
        "minimal_location_type": "Gene",
        "location_semantic": "target",
        "canonical_label": "amplification",
        "abbreviation": "amp",
        "is_umbrella": False,
        "regex_pattern": r"\b(?:amplification|amplified|copy\s+number\s+amplification|high\s+level\s+amplification)\b",
        "priority": 3,
    },
    "copy_number_loss": {
        "normalized_value": "copy_number_loss",
        "definition": "An umbrella copy-number alteration involving decreased genomic copy count.",
        "variant_class": "Copy Number Variant",
        "parent_mechanism": "copy_number_change",
        "minimal_location_type": "Gene",
        "location_semantic": "target",
        "canonical_label": "copy number loss",
        "abbreviation": "",
        "is_umbrella": True,
        "regex_pattern": r"\b(?:copy\s+number\s+loss|copy\s+loss|loss\s+of\s+copy\s+number)\b",
        "priority": 2,
    },
    "deletion_cna": {
        "normalized_value": "deletion_cna",
        "definition": "A copy-number loss affecting a whole gene or gene-level locus; context is needed to distinguish it from sequence deletion.",
        "variant_class": "Copy Number Variant",
        "parent_mechanism": "copy_number_loss",
        "minimal_location_type": "Gene",
        "location_semantic": "target",
        "canonical_label": "copy number deletion",
        "abbreviation": "",
        "is_umbrella": False,
        "regex_pattern": r"\b(?:homozygous\s+deletion|gene\s+deletion|copy\s+number\s+deletion|deep\s+deletion|deletion|del)\b",
        "priority": 3,
    },
    "exon_deletion_cna": {
        "normalized_value": "exon_deletion_cna",
        "definition": "A copy-number loss affecting one or more exons rather than the whole gene.",
        "variant_class": "Copy Number Variant",
        "parent_mechanism": "deletion_cna",
        "minimal_location_type": "Exon",
        "location_semantic": "target",
        "canonical_label": "copy number deletion",
        "abbreviation": "",
        "is_umbrella": False,
        "regex_pattern": r"\b(?:exons?\s+(?:\d+(?:\s*[-–]\s*\d+)?\s+)?deletion|exons?\s+(?:\d+(?:\s*[-–]\s*\d+)?\s+)?del|deletion|del)\b",
        "priority": 3,
    },
    "loss_of_heterozygosity": {
        "normalized_value": "loss of heterozygosity",
        "definition": "Loss of one parental allele or allele-specific signal at a locus.",
        "variant_class": "Copy Number Variant",
        "parent_mechanism": "copy_number_change",
        "minimal_location_type": "Gene",
        "location_semantic": "target",
        "canonical_label": "loh",
        "abbreviation": "loh",
        "is_umbrella": False,
        "regex_pattern": r"\b(?:loh|loss\s+of\s+heterozygosity)\b",
        "priority": 3,
    },
    "rearrangement": {
        "normalized_value": "rearrangement",
        "definition": "An umbrella structural alteration involving reorganization of genomic segments.",
        "variant_class": "Structural Variant",
        "parent_mechanism": "mutation",
        "minimal_location_type": "Gene",
        "location_semantic": "target",
        "canonical_label": "rearrangement",
        "abbreviation": "",
        "is_umbrella": True,
        "regex_pattern": r"\b(?:rearrangement|rearranged|re[\s\-]?arrangement|inversion)\b",
        "priority": 2,
    },
    "fusion": {
        "normalized_value": "fusion",
        "definition": "A structural alteration joining parts of two genes or loci into a fusion event.",
        "variant_class": "Structural Variant",
        "parent_mechanism": "rearrangement",
        "minimal_location_type": "Gene",
        "location_semantic": "target",
        "canonical_label": "fusion",
        "abbreviation": "fus",
        "is_umbrella": False,
        "regex_pattern": r"\b(?:fusion|fusions|fus)\b",
        "priority": 3,
    },
    "translocation": {
        "normalized_value": "translocation",
        "definition": "A structural alteration in which genomic material is relocated between chromosomal regions.",
        "variant_class": "Structural Variant",
        "parent_mechanism": "rearrangement",
        "minimal_location_type": "Gene",
        "location_semantic": "target",
        "canonical_label": "translocation",
        "abbreviation": "",
        "is_umbrella": False,
        "regex_pattern": r"\btranslocation\b",
        "priority": 3,
    },
    "mutation": {
        "normalized_value": "mutation",
        "definition": "An umbrella alteration term used when no more specific alteration mechanism can be inferred.",
        "variant_class": "Sequence Variant",
        "parent_mechanism": "mutation",
        "minimal_location_type": None,
        "location_semantic": None,
        "canonical_label": "mutation",
        "abbreviation": "mut",
        "is_umbrella": True,
        "regex_pattern": r"^(?:mutation\w*|unspe\w*|mutant|mut|alteration|altered|variant|undefined|intragenic)$",
        "priority": 1,
    },
    "wild_type": {
        "normalized_value": "wild_type",
        "definition": "A term indicating absence of the specified variant or presence of the reference sequence state.",
        "variant_class": "Sequence Variant",
        "parent_mechanism": "mutation",
        "minimal_location_type": None,
        "location_semantic": None,
        "canonical_label": "wild type",
        "abbreviation": "wt",
        "is_umbrella": False,
        "regex_pattern": r"\b(?:wild[\s\-]?type|wt)\b",
        "priority": 2,
    },
    "methylation": {
        "normalized_value": "methylation",
        "definition": "An umbrella epigenetic alteration involving DNA methylation state.",
        "variant_class": "Epigenetic Variant",
        "parent_mechanism": "mutation",
        "minimal_location_type": "Gene",
        "location_semantic": "target",
        "canonical_label": "methylation",
        "abbreviation": "",
        "is_umbrella": True,
        "regex_pattern": r"\bmethylation\b",
        "priority": 2,
    },
    "hypermethylation": {
        "normalized_value": "hypermethylation",
        "definition": "An epigenetic alteration involving increased DNA methylation.",
        "variant_class": "Epigenetic Variant",
        "parent_mechanism": "methylation",
        "minimal_location_type": "Gene",
        "location_semantic": "target",
        "canonical_label": "hypermethylation",
        "abbreviation": "",
        "is_umbrella": False,
        "regex_pattern": r"\bhypermethylation\b",
        "priority": 3,
    },
    "demethylation": {
        "normalized_value": "demethylation",
        "definition": "An epigenetic alteration involving decreased DNA methylation.",
        "variant_class": "Epigenetic Variant",
        "parent_mechanism": "methylation",
        "minimal_location_type": "Gene",
        "location_semantic": "target",
        "canonical_label": "demethylation",
        "abbreviation": "",
        "is_umbrella": False,
        "regex_pattern": r"\bdemethylation\b",
        "priority": 3,
    },
    "biallelic_inactivation": {
        "normalized_value": "biallelic_inactivation",
        "definition": "Inactivation of both alleles of a gene by mutation, deletion, epigenetic change, or a combination of mechanisms.",
        "variant_class": "Sequence Variant",
        "parent_mechanism": "mutation",
        "minimal_location_type": "Gene",
        "location_semantic": "target",
        "canonical_label": "biallelic inactivation",
        "abbreviation": "",
        "is_umbrella": False,
        "regex_pattern": r"\bbiallelic\s+inactivation\b",
        "priority": 3,
    },
    "expression": {
        "normalized_value": "expression",
        "definition": "An umbrella alteration describing gene or protein expression state.",
        "variant_class": "Expression Variant",
        "parent_mechanism": "mutation",
        "minimal_location_type": "Gene",
        "location_semantic": "target",
        "canonical_label": "expression",
        "abbreviation": "",
        "is_umbrella": False,
        "regex_pattern": r"\b(?:expression|expressed)\b",
        "priority": 2,
    },
    "absent": {
        "normalized_value": "absent",
        "definition": "An expression state indicating absence of detectable expression.",
        "variant_class": "Expression Variant",
        "parent_mechanism": "mutation",
        "minimal_location_type": "Gene",
        "location_semantic": "target",
        "canonical_label": "absent",
        "abbreviation": "",
        "is_umbrella": False,
        "regex_pattern": r"\b(?:absent)\b",
        "priority": 2,
    },
    "positive": {
        "normalized_value": "positive",
        "definition": "An expression state indicating positive detectable expression.",
        "variant_class": "Expression Variant",
        "parent_mechanism": "mutation",
        "minimal_location_type": "Gene",
        "location_semantic": "target",
        "canonical_label": "positive",
        "abbreviation": "",
        "is_umbrella": False,
        "regex_pattern": r"\b(?:positive)\b",
        "priority": 2,
    },
    "negative": {
        "normalized_value": "negative",
        "definition": "An expression state indicating negative or undetectable expression.",
        "variant_class": "Expression Variant",
        "parent_mechanism": "mutation",
        "minimal_location_type": "Gene",
        "location_semantic": "target",
        "canonical_label": "negative",
        "abbreviation": "",
        "is_umbrella": False,
        "regex_pattern": r"\b(?:negative)\b",
        "priority": 2,
    },
    "overexpression": {
        "normalized_value": "overexpression",
        "definition": "An expression alteration involving increased expression relative to the relevant reference state.",
        "variant_class": "Expression Variant",
        "parent_mechanism": "mutation",
        "minimal_location_type": "Gene",
        "location_semantic": "target",
        "canonical_label": "overexpression",
        "abbreviation": "",
        "is_umbrella": False,
        "regex_pattern": r"\b(?:overexpression|overexpressed|expression +)\b",
        "priority": 2,
    },
    "underexpression": {
        "normalized_value": "underexpression",
        "definition": "An expression alteration involving decreased expression relative to the relevant reference state.",
        "variant_class": "Expression Variant",
        "parent_mechanism": "mutation",
        "minimal_location_type": "Gene",
        "location_semantic": "target",
        "canonical_label": "underexpression",
        "abbreviation": "",
        "is_umbrella": False,
        "regex_pattern": r"\b(?:underexpression|underexpressed|undexpression|expression -|decreased\s+expression|low\s+expression)\b",
        "priority": 2,
    },
}


VARIANT_FUNCTION_ONTOLOGY: Dict[str, Dict[str, Any]] = {
    "gain_of_function": {
        "functional_domain": "protein_activity",
        "functional_value": "gain_of_function",
        "definition": "An umbrella functional effect in which a variant increases, creates, or constitutively activates protein activity.",
        "parent_functional": None,
        "canonical_label": "gain-of-function",
        "is_umbrella": True,
        "regex_pattern": r"\b(?:likely\s+)?(?:gain[\s\-]?of[\s\-]?function|gof)\b",
        "priority": 2,
    },
    "activating_mutation": {
        "functional_domain": "protein_activity",
        "functional_value": "activating_mutation",
        "definition": "A gain-of-function effect in which a variant activates protein activity or signaling.",
        "parent_functional": "gain_of_function",
        "canonical_label": "activating mutation",
        "is_umbrella": False,
        "regex_pattern": r"\bactivat(?:ing|ed)?(?:\s+mutation|\s+variant)?\b",
        "priority": 3,
    },
    "loss_of_function": {
        "functional_domain": "protein_activity",
        "functional_value": "loss_of_function",
        "definition": "An umbrella functional effect in which a variant reduces or abolishes protein function.",
        "parent_functional": None,
        "canonical_label": "loss-of-function",
        "is_umbrella": True,
        "regex_pattern": r"\b(?:likely\s+)?(?:loss[\s\-]?of[\s\-]?function|lof)\b",
        "priority": 2,
    },
    "inactivating_mutation": {
        "functional_domain": "protein_activity",
        "functional_value": "inactivating_mutation",
        "definition": "A loss-of-function effect in which a variant inactivates protein activity.",
        "parent_functional": "loss_of_function",
        "canonical_label": "inactivating mutation",
        "is_umbrella": False,
        "regex_pattern": r"\binactivat(?:ing|ed)?(?:\s+mutation|\s+variant)?\b",
        "priority": 3,
    },
    "switch_of_function": {
        "functional_domain": "protein_activity",
        "functional_value": "switch_of_function",
        "definition": "A functional effect in which a variant changes the qualitative activity or specificity of a protein.",
        "parent_functional": None,
        "canonical_label": "switch-of-function",
        "is_umbrella": False,
        "regex_pattern": r"\b(?:likely\s+)?(?:switch[\s\-]?of[\s\-]?function)\b",
        "priority": 2,
    },
    "neutral": {
        "functional_domain": "protein_activity",
        "functional_value": "neutral",
        "definition": "A functional interpretation indicating no substantial effect on protein activity.",
        "parent_functional": None,
        "canonical_label": "neutral mutation",
        "is_umbrella": False,
        "regex_pattern": r"\b(?:neutral|likely\s+neutral)\b",
        "priority": 2,
    },
    "oncogenic": {
        "functional_domain": "oncogenic_assertion",
        "functional_value": "oncogenic",
        "definition": "An umbrella oncogenicity assertion that a variant contributes to cancer development or progression.",
        "parent_functional": None,
        "canonical_label": "oncogenic mutation",
        "is_umbrella": True,
        "regex_pattern": r"\b(?:oncogenic|oncogenic\s+mutation|oncogenic\s+variant)\b",
        "priority": 2,
    },
    "likely_oncogenic": {
        "functional_domain": "oncogenic_assertion",
        "functional_value": "likely_oncogenic",
        "definition": "An oncogenicity assertion that a variant is likely to contribute to cancer development or progression.",
        "parent_functional": "oncogenic",
        "canonical_label": "likely oncogenic mutation",
        "is_umbrella": False,
        "regex_pattern": r"\blikely\s+oncogenic\b",
        "priority": 3,
    },
    "benign_or_neutral": {
        "functional_domain": "oncogenic_assertion",
        "functional_value": "benign_or_neutral",
        "definition": "An oncogenicity assertion that a variant is benign, likely benign, or not expected to drive cancer.",
        "parent_functional": None,
        "canonical_label": "benign or neutral mutation",
        "is_umbrella": False,
        "regex_pattern": r"\b(?:benign|likely\s+benign|benign\s+or\s+neutral)\b",
        "priority": 2,
    },
    "inconclusive": {
        "functional_domain": "oncogenic_assertion",
        "functional_value": "inconclusive",
        "definition": "An assertion indicating insufficient or conflicting evidence to classify functional or oncogenic impact.",
        "parent_functional": None,
        "canonical_label": "inconclusive mutation",
        "is_umbrella": False,
        "regex_pattern": r"\b(?:inconclusive|uncertain\s+significance|vus|variant\s+of\s+unknown\s+significance)\b",
        "priority": 2,
    },
}


